version: "3.5"
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
      - INFLUXDB_DB="telemetry"
    volumes:
      - db-data:/var/lib/influxdb
    restart: unless-stopped
    networks:
      - telemetry-server
  grafana:
    build: ./grafana 
    container_name: grafana
    depends_on:
      - "influxdb"
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    networks:
      - telemetry-server
  server: 
    image: "golang:1.11.2"
    container_name: server
    environment:
      - IN_DOCKER=true
    depends_on:
      - "influxdb"
    working_dir: /app
    volumes: 
      - ./server:/app
      - cache:/go
    command: bash -c "go run main.go"
    ports:
      - "8888:8888"
      - "6001:6001"
    restart: unless-stopped 
    networks:
      - telemetry-server
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - "server"
      - "grafana"
      - "jenkins"
    volumes:
      - ./nginx/conf.d/prod:/etc/nginx/conf.d
      - /etc/letsencrypt/:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped 
    networks:
      - telemetry-server
  jenkins:
    build: ./jenkins
    container_name: jenkins
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/opt/telemetry-server
    ports:
      - "8080:8080"
    networks:
      - telemetry-server
volumes:
  cache:
  db-data:
  grafana-storage:
  jenkins-home:
networks:
  telemetry-server:
    name: telemetry-server
